/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "proto_files/steppermotors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(steppers_pb_motors, steppers_pb_motors, AUTO)


PB_BIND(steppers_pb_motors_MotorX, steppers_pb_motors_MotorX, AUTO)


PB_BIND(steppers_pb_motors_MotorY, steppers_pb_motors_MotorY, AUTO)


PB_BIND(steppers_pb_motors_MotorZ, steppers_pb_motors_MotorZ, AUTO)







