/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "proto_files/steppermotors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_motors, pb_motors, AUTO)


PB_BIND(pb_motors_MotorX, pb_motors_MotorX, AUTO)


PB_BIND(pb_motors_MotorY, pb_motors_MotorY, AUTO)


PB_BIND(pb_motors_MotorZ, pb_motors_MotorZ, AUTO)







